version: 2.1

jobs:
  docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build .

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
