version: 2.1

jobs:
  docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.11"
          docker_layer_caching: true
      - run: |
          export DOCKER_BUILDKIT=1
          docker build .

  docker-image-2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.11"
          docker_layer_caching: true
      - run: |
          docker build -f Dockerfile.fedora35 .

workflows:
  docker-image-workflow:
    jobs:
      - docker-image
      - docker-image-2
